"use client";

/**
 * Generates and downloads a PDF receipt for a transaction.
 * Uses the browser's built-in print-to-PDF capability via a hidden iframe.
 */
export interface ReceiptData {
  id: string;
  title: string;
  date: string;
  amount: string;
  type: "credit" | "debit";
  status: string;
  userName: string;
  userEmail?: string;
}

export function generateReceipt(tx: ReceiptData) {
  const receiptHTML = `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Receipt - ${tx.id}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Segoe UI', -apple-system, sans-serif; background: #fff; color: #1a1a2e; padding: 40px; }
  .receipt { max-width: 500px; margin: 0 auto; border: 1px solid #e5e7eb; border-radius: 16px; overflow: hidden; }
  .header { background: linear-gradient(135deg, #059669, #10b981); color: white; padding: 32px 24px; text-align: center; }
  .header h1 { font-size: 28px; font-weight: 800; letter-spacing: 2px; }
  .header p { font-size: 13px; opacity: 0.85; margin-top: 4px; }
  .badge { display: inline-block; background: rgba(255,255,255,0.2); color: white; font-size: 11px; font-weight: 600; padding: 4px 12px; border-radius: 20px; margin-top: 12px; text-transform: uppercase; letter-spacing: 1px; }
  .body { padding: 24px; }
  .amount-section { text-align: center; padding: 20px 0; border-bottom: 1px dashed #e5e7eb; margin-bottom: 20px; }
  .amount { font-size: 36px; font-weight: 800; color: ${tx.type === "credit" ? "#059669" : "#ef4444"}; }
  .amount-label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
  .details { list-style: none; }
  .details li { display: flex; justify-content: space-between; padding: 12px 0; border-bottom: 1px solid #f3f4f6; font-size: 14px; }
  .details li:last-child { border-bottom: none; }
  .label { color: #6b7280; }
  .value { font-weight: 600; color: #1a1a2e; }
  .status { display: inline-flex; align-items: center; gap: 4px; padding: 3px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; }
  .status-success { background: #d1fae5; color: #059669; }
  .status-pending { background: #fef3c7; color: #d97706; }
  .footer { padding: 16px 24px; background: #f9fafb; text-align: center; font-size: 11px; color: #9ca3af; border-top: 1px solid #f3f4f6; }
  .footer strong { color: #6b7280; }
  @media print { body { padding: 0; } .receipt { border: none; } }
</style>
</head>
<body>
<div class="receipt">
  <div class="header">
    <h1>HANDI</h1>
    <p>Transaction Receipt</p>
    <div class="badge">${tx.type === "credit" ? "Payment Received" : "Payment Sent"}</div>
  </div>
  <div class="body">
    <div class="amount-section">
      <div class="amount">${tx.amount}</div>
      <div class="amount-label">${tx.type === "credit" ? "Amount Received" : "Amount Debited"}</div>
    </div>
    <ul class="details">
      <li><span class="label">Transaction ID</span><span class="value">#${tx.id}</span></li>
      <li><span class="label">Description</span><span class="value">${tx.title}</span></li>
      <li><span class="label">Date</span><span class="value">${tx.date}</span></li>
      <li><span class="label">Name</span><span class="value">${tx.userName}</span></li>
      ${tx.userEmail ? `<li><span class="label">Email</span><span class="value">${tx.userEmail}</span></li>` : ""}
      <li><span class="label">Status</span><span class="value"><span class="status ${tx.status === "Success" ? "status-success" : "status-pending"}">${tx.status === "Success" ? "✓ " : "⏳ "}${tx.status}</span></span></li>
    </ul>
  </div>
  <div class="footer">
    <p>This is an electronic receipt generated by <strong>HANDI</strong></p>
    <p style="margin-top:4px;">© ${new Date().getFullYear()} HANDI by AIXILCOILS NEXTGENSOFT — All rights reserved</p>
  </div>
</div>
</body>
</html>`;

  // Create a blob and open in new window for printing/saving
  const blob = new Blob([receiptHTML], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const printWindow = window.open(url, "_blank", "width=600,height=800");
  if (printWindow) {
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        URL.revokeObjectURL(url);
      }, 300);
    };
  }
}
