// constants/categories.ts
// Complete list of 50+ service categories for HANDI app

export interface Category {
  id: string;
  name: string;
  icon: string; // Ionicons name
  color: string;
  description: string;
  featured: boolean;
  subServices?: string[];
  emergencyAvailable?: boolean; // 24/7 emergency service available
}

// ================================
// 17 Primary Featured Categories (with images)
// ================================
export const FEATURED_CATEGORIES: Category[] = [
  {
    id: "electrician",
    name: "Electrician",
    icon: "flash",
    color: "#FEF3C7",
    description: "Wiring, repairs, installations, and electrical maintenance",
    featured: true,
    subServices: [
      "Wiring Installation",
      "Socket/Switch Repair",
      "Circuit Breaker Fix",
      "Generator Wiring",
      "Electrical Inspection",
    ],
    emergencyAvailable: true,
  },
  {
    id: "interior-designer",
    name: "Interior Designer",
    icon: "color-palette",
    color: "#FCE7F3",
    description: "Home and office interior design and decoration",
    featured: true,
    subServices: [
      "Home Design",
      "Office Design",
      "Space Planning",
      "Color Consultation",
      "3D Rendering",
    ],
  },
  {
    id: "furniture-maker",
    name: "Furniture Maker",
    icon: "cube",
    color: "#FED7AA",
    description: "Custom furniture design and crafting",
    featured: true,
    subServices: [
      "Custom Furniture",
      "Cabinet Making",
      "Wardrobe Design",
      "Shelf Installation",
      "Wood Repair",
    ],
  },
  {
    id: "barber",
    name: "Barber",
    icon: "cut",
    color: "#DBEAFE",
    description: "Professional haircuts and grooming for men",
    featured: true,
    subServices: [
      "Haircut",
      "Beard Trim",
      "Shave",
      "Hair Styling",
      "Kids Haircut",
    ],
  },
  {
    id: "masseuse",
    name: "Masseuse / Spa",
    icon: "flower",
    color: "#D1FAE5",
    description: "Massage therapy and spa treatments",
    featured: true,
    subServices: [
      "Full Body Massage",
      "Sports Massage",
      "Deep Tissue",
      "Aromatherapy",
      "Facial Treatment",
    ],
  },
  {
    id: "tiler",
    name: "Tiler",
    icon: "grid",
    color: "#E0E7FF",
    description: "Floor and wall tiling services",
    featured: true,
    subServices: [
      "Floor Tiling",
      "Wall Tiling",
      "Bathroom Tiles",
      "Kitchen Backsplash",
      "Tile Repair",
    ],
  },
  {
    id: "chef",
    name: "Chef / Cook",
    icon: "restaurant",
    color: "#FEE2E2",
    description: "Personal chef and cooking services",
    featured: true,
    subServices: [
      "Private Chef",
      "Event Catering",
      "Meal Prep",
      "Cooking Classes",
      "Special Diet Meals",
    ],
  },
  {
    id: "architect",
    name: "Architect",
    icon: "business",
    color: "#CCFBF1",
    description: "Architectural design and building plans",
    featured: true,
    subServices: [
      "Building Design",
      "Renovation Plans",
      "3D Modeling",
      "Permit Drawings",
      "Site Inspection",
    ],
  },
  {
    id: "borehole",
    name: "Borehole Drilling",
    icon: "water",
    color: "#CFFAFE",
    description: "Water borehole drilling and maintenance",
    featured: true,
    subServices: [
      "Borehole Drilling",
      "Pump Installation",
      "Water Treatment",
      "Maintenance",
      "Tank Installation",
    ],
  },
  {
    id: "car-wash",
    name: "Car Wash",
    icon: "car-sport",
    color: "#E0E7FF",
    description: "Mobile car washing and detailing",
    featured: true,
    subServices: [
      "Basic Wash",
      "Full Detailing",
      "Interior Cleaning",
      "Engine Wash",
      "Polish & Wax",
    ],
  },
  {
    id: "tailor",
    name: "Tailor / Fashion",
    icon: "shirt",
    color: "#EDE9FE",
    description: "Custom tailoring and alterations",
    featured: true,
    subServices: [
      "Custom Suits",
      "Traditional Wear",
      "Alterations",
      "Dress Making",
      "Uniforms",
    ],
  },
  {
    id: "solar",
    name: "Solar Panel Tech",
    icon: "sunny",
    color: "#FEF9C3",
    description: "Solar panel installation and maintenance",
    featured: true,
    subServices: [
      "Panel Installation",
      "Inverter Setup",
      "Battery Bank",
      "System Maintenance",
      "Consultation",
    ],
  },
  {
    id: "hair-stylist",
    name: "Hair Stylist",
    icon: "sparkles",
    color: "#FFE4E6",
    description: "Professional hair styling for women",
    featured: true,
    subServices: [
      "Braiding",
      "Weaving",
      "Hair Treatment",
      "Coloring",
      "Locs",
      "Wig Installation",
    ],
  },
  {
    id: "waste-removal",
    name: "Waste Removal",
    icon: "trash",
    color: "#DCFCE7",
    description: "Waste collection and disposal services",
    featured: true,
    subServices: [
      "Home Waste",
      "Commercial Waste",
      "Bulk Removal",
      "Recycling",
      "Garden Waste",
    ],
  },
  {
    id: "laundry",
    name: "Laundry Service",
    icon: "water-outline",
    color: "#DBEAFE",
    description: "Wash, dry, and iron services",
    featured: true,
    subServices: [
      "Wash & Fold",
      "Dry Cleaning",
      "Ironing",
      "Stain Removal",
      "Pickup & Delivery",
    ],
  },
  {
    id: "fumigation",
    name: "Fumigation",
    icon: "bug",
    color: "#F0FDF4",
    description: "Pest control and fumigation",
    featured: true,
    subServices: [
      "Home Fumigation",
      "Office Fumigation",
      "Termite Control",
      "Rodent Control",
      "Mosquito Treatment",
    ],
  },
  {
    id: "laptop-repair",
    name: "Laptop Repair",
    icon: "laptop",
    color: "#F3E8FF",
    description: "Computer and laptop repair services",
    featured: true,
    subServices: [
      "Screen Repair",
      "Keyboard Fix",
      "Software Issues",
      "Data Recovery",
      "Upgrade",
      "Virus Removal",
    ],
  },
];

// ================================
// 34+ Additional Categories
// ================================
export const ADDITIONAL_CATEGORIES: Category[] = [
  {
    id: "plumber",
    name: "Plumber",
    icon: "construct",
    color: "#BAE6FD",
    description: "Plumbing repairs and installations",
    featured: false,
    subServices: [
      "Pipe Repair",
      "Drain Cleaning",
      "Toilet Fix",
      "Water Heater",
      "Leak Detection",
    ],
    emergencyAvailable: true,
  },
  {
    id: "mason",
    name: "Mason",
    icon: "cube-outline",
    color: "#FED7AA",
    description: "Masonry and bricklaying services",
    featured: false,
    subServices: [
      "Block Laying",
      "Plastering",
      "Concrete Work",
      "Wall Repair",
      "Foundation Work",
    ],
  },
  {
    id: "welder",
    name: "Welder",
    icon: "flame",
    color: "#FEE2E2",
    description: "Welding and metal fabrication",
    featured: false,
    subServices: [
      "Gate Fabrication",
      "Burglar Proof",
      "Metal Repair",
      "Balustrades",
      "Window Frames",
    ],
  },
  {
    id: "refrigerator-repair",
    name: "Refrigerator Repair",
    icon: "snow",
    color: "#CFFAFE",
    description: "Fridge and freezer repair",
    featured: false,
    subServices: [
      "Compressor Repair",
      "Gas Refill",
      "Thermostat Fix",
      "Door Seal",
      "General Service",
    ],
  },
  {
    id: "mechanic",
    name: "Mechanic",
    icon: "settings",
    color: "#E5E7EB",
    description: "Auto repair and maintenance",
    featured: false,
    subServices: [
      "Engine Repair",
      "Brake Service",
      "Oil Change",
      "Diagnostics",
      "AC Repair",
      "Battery",
    ],
  },
  {
    id: "cctv",
    name: "CCTV Installer",
    icon: "videocam",
    color: "#E0E7FF",
    description: "Security camera installation",
    featured: false,
    subServices: [
      "Camera Installation",
      "DVR Setup",
      "Remote Viewing",
      "Maintenance",
      "Upgrade",
    ],
  },
  {
    id: "deep-cleaning",
    name: "Deep Cleaning",
    icon: "sparkles",
    color: "#DBEAFE",
    description: "Thorough home and office cleaning",
    featured: false,
    subServices: [
      "Home Deep Clean",
      "Office Cleaning",
      "Move-In/Out Clean",
      "Post-Construction",
      "Spring Cleaning",
    ],
  },
  {
    id: "upholstery",
    name: "Upholstery Cleaning",
    icon: "bed",
    color: "#FCE7F3",
    description: "Furniture and fabric cleaning",
    featured: false,
    subServices: [
      "Sofa Cleaning",
      "Mattress Cleaning",
      "Carpet Cleaning",
      "Curtain Cleaning",
      "Car Interior",
    ],
  },
  {
    id: "water-tank",
    name: "Water Tank Cleaning",
    icon: "water",
    color: "#A5F3FC",
    description: "Overhead and underground tank cleaning",
    featured: false,
    subServices: [
      "Tank Cleaning",
      "Disinfection",
      "Repair",
      "Installation",
      "Maintenance",
    ],
  },
  {
    id: "nail-tech",
    name: "Nail Technician",
    icon: "hand-left",
    color: "#FBCFE8",
    description: "Manicure, pedicure, and nail art",
    featured: false,
    subServices: [
      "Manicure",
      "Pedicure",
      "Nail Art",
      "Gel Nails",
      "Acrylic Nails",
      "Nail Repair",
    ],
  },
  {
    id: "landscaper",
    name: "Landscaper",
    icon: "leaf",
    color: "#BBF7D0",
    description: "Garden design and maintenance",
    featured: false,
    subServices: [
      "Garden Design",
      "Lawn Mowing",
      "Hedge Trimming",
      "Planting",
      "Irrigation",
      "Tree Trimming",
    ],
  },
  {
    id: "pool-maintenance",
    name: "Pool Maintenance",
    icon: "swimming-pool",
    color: "#BAE6FD",
    description: "Swimming pool cleaning and maintenance",
    featured: false,
    subServices: [
      "Pool Cleaning",
      "Chemical Balance",
      "Filter Maintenance",
      "Pump Repair",
      "Tile Cleaning",
    ],
  },
  {
    id: "wifi-tech",
    name: "WiFi Technician",
    icon: "wifi",
    color: "#DDD6FE",
    description: "Network setup and troubleshooting",
    featured: false,
    subServices: [
      "Router Setup",
      "Network Extension",
      "Speed Optimization",
      "Security Setup",
      "Troubleshooting",
    ],
  },
  {
    id: "smart-home",
    name: "Smart Home",
    icon: "home",
    color: "#C7D2FE",
    description: "Smart home device installation",
    featured: false,
    subServices: [
      "Smart Lights",
      "Smart Locks",
      "Home Automation",
      "Voice Assistant",
      "Smart Thermostat",
    ],
  },
  {
    id: "tv-mounting",
    name: "TV Mounting",
    icon: "tv",
    color: "#E5E7EB",
    description: "TV wall mounting and setup",
    featured: false,
    subServices: [
      "Wall Mounting",
      "Cable Management",
      "Sound System",
      "Antenna Setup",
      "Projector Install",
    ],
  },
  {
    id: "roofer",
    name: "Roofer",
    icon: "home-outline",
    color: "#FED7AA",
    description: "Roof repair and installation",
    featured: false,
    subServices: [
      "Roof Repair",
      "New Roofing",
      "Leak Fix",
      "Gutter Installation",
      "Roof Painting",
    ],
  },
  {
    id: "floor-installer",
    name: "Floor Installer",
    icon: "layers",
    color: "#FEE2E2",
    description: "Floor installation and repair",
    featured: false,
    subServices: [
      "Laminate Flooring",
      "Hardwood",
      "Vinyl",
      "Carpet",
      "Floor Sanding",
      "Repair",
    ],
  },
  {
    id: "furniture-assembly",
    name: "Furniture Assembly",
    icon: "build",
    color: "#FECACA",
    description: "Furniture assembly and installation",
    featured: false,
    subServices: [
      "IKEA Assembly",
      "Bed Assembly",
      "Desk Setup",
      "Shelf Mounting",
      "Wardrobe Assembly",
    ],
  },
  {
    id: "errand-runner",
    name: "Errand Runner",
    icon: "walk",
    color: "#A7F3D0",
    description: "Personal errands and deliveries",
    featured: false,
    subServices: [
      "Shopping",
      "Document Pickup",
      "Package Delivery",
      "Queue Service",
      "Bill Payment",
    ],
  },
  {
    id: "vehicle-wash",
    name: "Vehicle Wash",
    icon: "car",
    color: "#BFDBFE",
    description: "Vehicle cleaning at your location",
    featured: false,
    subServices: [
      "Car Wash",
      "Truck Wash",
      "Bus Wash",
      "Motorcycle Wash",
      "Boat Cleaning",
    ],
  },
  {
    id: "cobbler",
    name: "Cobbler",
    icon: "footsteps",
    color: "#F5D0FE",
    description: "Shoe repair and restoration",
    featured: false,
    subServices: [
      "Sole Repair",
      "Heel Replacement",
      "Leather Repair",
      "Shoe Cleaning",
      "Bag Repair",
    ],
  },
  {
    id: "event-decorator",
    name: "Event Decorator",
    icon: "gift",
    color: "#FBD5E8",
    description: "Event and party decoration",
    featured: false,
    subServices: [
      "Wedding Decor",
      "Birthday Setup",
      "Corporate Events",
      "Balloon Decor",
      "Flower Arrangement",
    ],
  },
  {
    id: "personal-assistant",
    name: "Personal Assistant",
    icon: "person",
    color: "#D1D5DB",
    description: "Administrative and personal assistance",
    featured: false,
    subServices: [
      "Scheduling",
      "Travel Booking",
      "Research",
      "Admin Support",
      "Organization",
    ],
  },
  {
    id: "ac-repair",
    name: "AC Repair",
    icon: "thermometer",
    color: "#CFFAFE",
    description: "Air conditioner repair and servicing",
    featured: false,
    subServices: [
      "AC Servicing",
      "Gas Refill",
      "Installation",
      "Filter Cleaning",
      "Compressor Repair",
    ],
    emergencyAvailable: true,
  },
  {
    id: "painter",
    name: "Painter",
    icon: "brush",
    color: "#FDE68A",
    description: "Interior and exterior painting",
    featured: false,
    subServices: [
      "Interior Painting",
      "Exterior Painting",
      "Wallpaper",
      "Texture Coating",
      "Touch-ups",
    ],
  },
  {
    id: "carpenter",
    name: "Carpenter",
    icon: "hammer",
    color: "#FDBA74",
    description: "Woodwork and carpentry services",
    featured: false,
    subServices: [
      "Door Repair",
      "Window Fix",
      "Custom Woodwork",
      "Deck Building",
      "Staircase",
    ],
  },
  {
    id: "pest-control",
    name: "Pest Control",
    icon: "bug-outline",
    color: "#D9F99D",
    description: "General pest control services",
    featured: false,
    subServices: [
      "Cockroach",
      "Ant Control",
      "Bed Bugs",
      "Spider Control",
      "Snake Removal",
    ],
  },
  {
    id: "appliance-repair",
    name: "Appliance Repair",
    icon: "hardware-chip",
    color: "#E2E8F0",
    description: "Home appliance repair",
    featured: false,
    subServices: [
      "Washing Machine",
      "Dryer",
      "Microwave",
      "Oven",
      "Dishwasher",
      "Blender",
    ],
  },
  {
    id: "phone-repair",
    name: "Phone Repair",
    icon: "phone-portrait",
    color: "#C7D2FE",
    description: "Mobile phone repair services",
    featured: false,
    subServices: [
      "Screen Repair",
      "Battery Replacement",
      "Charging Port",
      "Software Fix",
      "Data Recovery",
    ],
  },
  {
    id: "makeup-artist",
    name: "Makeup Artist",
    icon: "color-wand",
    color: "#FECDD3",
    description: "Professional makeup services",
    featured: false,
    subServices: [
      "Bridal Makeup",
      "Event Makeup",
      "Natural Look",
      "Special Effects",
      "Makeup Lessons",
    ],
  },
  {
    id: "photographer",
    name: "Photographer",
    icon: "camera",
    color: "#FED7AA",
    description: "Photography services",
    featured: false,
    subServices: [
      "Event Photography",
      "Portrait",
      "Product Shots",
      "Video",
      "Drone Photography",
    ],
  },
  {
    id: "dj",
    name: "DJ Services",
    icon: "musical-notes",
    color: "#E9D5FF",
    description: "DJ and music entertainment",
    featured: false,
    subServices: [
      "Wedding DJ",
      "Party DJ",
      "Corporate Events",
      "MC Services",
      "Sound System",
    ],
  },
  {
    id: "security",
    name: "Security Guard",
    icon: "shield-checkmark",
    color: "#D1D5DB",
    description: "Security personnel services",
    featured: false,
    subServices: [
      "Event Security",
      "Personal Bodyguard",
      "Night Watch",
      "Property Security",
      "VIP Protection",
    ],
  },
  {
    id: "tutor",
    name: "Private Tutor",
    icon: "book",
    color: "#FEF3C7",
    description: "Educational tutoring services",
    featured: false,
    subServices: [
      "Math Tutoring",
      "English",
      "Science",
      "Exam Prep",
      "Music Lessons",
      "Language",
    ],
  },
  {
    id: "fitness-trainer",
    name: "Fitness Trainer",
    icon: "fitness",
    color: "#DCFCE7",
    description: "Personal training and fitness",
    featured: false,
    subServices: [
      "Personal Training",
      "Group Fitness",
      "Yoga",
      "Weight Loss",
      "Strength Training",
    ],
  },
  {
    id: "gardener",
    name: "Gardener",
    icon: "leaf",
    color: "#BBF7D0",
    description: "Garden care and maintenance",
    featured: false,
    subServices: [
      "Lawn Care",
      "Weeding",
      "Planting",
      "Pruning",
      "Fertilizing",
      "Watering",
    ],
  },
  {
    id: "driver",
    name: "Driver",
    icon: "car-outline",
    color: "#F0F0F0",
    description: "Professional driving services",
    featured: false,
    subServices: [
      "Personal Driver",
      "Event Driver",
      "Airport Transfer",
      "Long Distance",
      "Delivery",
    ],
  },
];

// ================================
// Combined Categories
// ================================
export const ALL_CATEGORIES: Category[] = [
  ...FEATURED_CATEGORIES,
  ...ADDITIONAL_CATEGORIES,
];

// ================================
// Helper Functions
// ================================
export function getCategoryById(id: string): Category | undefined {
  return ALL_CATEGORIES.find((cat) => cat.id === id);
}

export function getCategoriesByIds(ids: string[]): Category[] {
  return ALL_CATEGORIES.filter((cat) => ids.includes(cat.id));
}

export function searchCategories(query: string): Category[] {
  const normalizedQuery = query.toLowerCase().trim();
  return ALL_CATEGORIES.filter(
    (cat) =>
      cat.name.toLowerCase().includes(normalizedQuery) ||
      cat.description.toLowerCase().includes(normalizedQuery) ||
      cat.subServices?.some((s) => s.toLowerCase().includes(normalizedQuery)),
  );
}

export function getFeaturedCategories(): Category[] {
  return FEATURED_CATEGORIES;
}

export function getCategorySubServices(categoryId: string): string[] {
  const category = getCategoryById(categoryId);
  return category?.subServices || [];
}

// Export count for display
export const TOTAL_CATEGORY_COUNT = ALL_CATEGORIES.length;
