export const MOCK_SERVICES = [
  {
    id: "ps1",
    name: "Home Fumigation",
    category: "Pest Control",
    price: "₦20,000",
    status: "active" as const,
    bookings: 12,
    rating: 4.8,
    image: "/images/services/fumigation.jpg",
    duration: "2-3 hours",
  },
  {
    id: "ps2",
    name: "Deep Cleaning",
    category: "Cleaning",
    price: "₦15,000",
    status: "active" as const,
    bookings: 28,
    rating: 4.9,
    image: "/images/services/cleaning.jpg",
    duration: "3-4 hours",
  },
  {
    id: "ps3",
    name: "Kitchen Renovation",
    category: "Construction",
    price: "₦120,000",
    status: "paused" as const,
    bookings: 5,
    rating: 4.7,
    image: "/images/services/renovation.jpg",
    duration: "5-7 days",
  },
  {
    id: "ps4",
    name: "Electrical Wiring",
    category: "Electrical",
    price: "₦26,000",
    status: "active" as const,
    bookings: 18,
    rating: 4.8,
    image: "/images/services/electrical.jpg",
    duration: "4-6 hours",
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "pb1",
    service: "Home Fumigation",
    client: "Adaobi Chen",
    date: "2026-02-26",
    time: "10:00 AM",
    location: "Lekki, Lagos",
    status: "pending" as const,
    amount: "₦20,000",
    avatar: null,
    phone: "+234 801 234 5678",
    rating: 4.5,
    previousBookings: 3,
  },
  {
    id: "pb2",
    service: "Deep Cleaning",
    client: "Emeka Johnson",
    date: "2026-02-22",
    time: "2:00 PM",
    location: "Ikeja, Lagos",
    status: "confirmed" as const,
    amount: "₦15,000",
    avatar: null,
    phone: "+234 802 345 6789",
    rating: 4.8,
    previousBookings: 7,
  },
  {
    id: "pb3",
    service: "Kitchen Renovation",
    client: "Sarah Williams",
    date: "2026-02-15",
    time: "9:00 AM",
    location: "Victoria Island, Lagos",
    status: "completed" as const,
    amount: "₦45,000",
    avatar: null,
    phone: "+234 803 456 7890",
    rating: 5.0,
    previousBookings: 1,
  },
  {
    id: "pb4",
    service: "Deep Cleaning",
    client: "Tunde Bakare",
    date: "2026-02-28",
    time: "11:00 AM",
    location: "Surulere, Lagos",
    status: "pending" as const,
    amount: "₦15,000",
    avatar: null,
    phone: "+234 804 567 8901",
    rating: 4.2,
    previousBookings: 2,
  },
  {
    id: "pb5",
    service: "Home Fumigation",
    client: "Grace Obi",
    date: "2026-02-10",
    time: "3:00 PM",
    location: "Yaba, Lagos",
    status: "completed" as const,
    amount: "₦20,000",
    avatar: null,
    phone: "+234 805 678 9012",
    rating: 4.9,
    previousBookings: 5,
  },
  {
    id: "pb6",
    service: "Kitchen Renovation",
    client: "James Nwachukwu",
    date: "2026-01-30",
    time: "8:00 AM",
    location: "Ajah, Lagos",
    status: "cancelled" as const,
    amount: "₦120,000",
    avatar: null,
    phone: "+234 806 789 0123",
    rating: 3.8,
    previousBookings: 1,
  },
  {
    id: "pb7",
    service: "Electrical Wiring",
    client: "Ada Obi",
    date: "2026-03-06",
    time: "1:00 PM",
    location: "Lagos Island",
    status: "confirmed" as const,
    amount: "₦26,000",
    avatar: null,
    phone: "+234 807 890 1234",
    rating: 4.7,
    previousBookings: 4,
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: "pt1",
    title: "Payment — Deep Cleaning",
    booking: "pb2",
    client: "Emeka Johnson",
    date: "Today, 2:30 PM",
    amount: "+ ₦15,000",
    type: "credit" as const,
    status: "completed" as const,
  },
  {
    id: "pt2",
    title: "Withdrawal to GTBank",
    booking: null,
    client: null,
    date: "Feb 19, 2026",
    amount: "- ₦50,000",
    type: "debit" as const,
    status: "completed" as const,
  },
  {
    id: "pt3",
    title: "Payment — Fumigation",
    booking: "pb5",
    client: "Grace Obi",
    date: "Feb 18, 2026",
    amount: "+ ₦20,000",
    type: "credit" as const,
    status: "completed" as const,
  },
  {
    id: "pt4",
    title: "Commission Fee",
    booking: null,
    client: null,
    date: "Feb 18, 2026",
    amount: "- ₦2,000",
    type: "debit" as const,
    status: "completed" as const,
  },
  {
    id: "pt5",
    title: "Payment — Kitchen Reno",
    booking: "pb3",
    client: "Sarah Williams",
    date: "Feb 15, 2026",
    amount: "+ ₦45,000",
    type: "credit" as const,
    status: "completed" as const,
  },
  {
    id: "pt6",
    title: "Payment — Electrical Wiring",
    booking: "pb7",
    client: "Ada Obi",
    amount: "+ ₦26,000",
    date: "Mar 6, 2026",
    type: "credit" as const,
    status: "pending" as const,
  },
];

export const MOCK_REVIEWS = [
  {
    id: "r1",
    customer: "Ada Obi",
    avatar: null,
    service: "Electrical Wiring",
    rating: 5,
    text: "Excellent electrician. Arrived on time and fixed everything quickly. Very professional and clean work.",
    date: "May 2025",
    reply: null,
  },
  {
    id: "r2",
    customer: "Grace Obi",
    avatar: null,
    service: "Home Fumigation",
    rating: 5,
    text: "Very thorough fumigation service. No pests since the treatment. Highly recommend!",
    date: "Feb 2026",
    reply: "Thank you Grace! Glad the treatment worked well.",
  },
  {
    id: "r3",
    customer: "Emeka Johnson",
    avatar: null,
    service: "Deep Cleaning",
    rating: 4,
    text: "Good cleaning service. Could improve on attention to corners but overall satisfied.",
    date: "Feb 2026",
    reply: null,
  },
  {
    id: "r4",
    customer: "Sarah Williams",
    avatar: null,
    service: "Kitchen Renovation",
    rating: 5,
    text: "Amazing renovation work. Transformed our kitchen completely. Worth every naira!",
    date: "Feb 2026",
    reply: "Thank you Sarah! It was a pleasure working on your kitchen.",
  },
  {
    id: "r5",
    customer: "Tunde Bakare",
    avatar: null,
    service: "Deep Cleaning",
    rating: 3,
    text: "Service was okay but arrived 30 minutes late. Cleaning quality was decent.",
    date: "Jan 2026",
    reply: null,
  },
  {
    id: "r6",
    customer: "Adaobi Chen",
    avatar: null,
    service: "Home Fumigation",
    rating: 5,
    text: "Best pest control service in Lagos. Very professional and effective.",
    date: "Jan 2026",
    reply: null,
  },
];

export const MOCK_CONVERSATIONS = [
  {
    id: "c1",
    customer: "Ada Obi",
    avatar: null,
    lastMessage: "Hi, can you come earlier tomorrow?",
    time: "10:30 AM",
    unread: 2,
    messages: [
      { id: "m1", sender: "customer", text: "Hi, I booked electrical wiring for tomorrow", time: "9:00 AM" },
      { id: "m2", sender: "provider", text: "Yes! I have it scheduled for 1:00 PM", time: "9:15 AM" },
      { id: "m3", sender: "customer", text: "Is it possible to come around 10 AM instead?", time: "10:20 AM" },
      { id: "m4", sender: "customer", text: "Hi, can you come earlier tomorrow?", time: "10:30 AM" },
    ],
  },
  {
    id: "c2",
    customer: "Emeka Johnson",
    avatar: null,
    lastMessage: "Thank you! The place looks great",
    time: "Yesterday",
    unread: 0,
    messages: [
      { id: "m5", sender: "provider", text: "Hi Emeka, just confirming your deep cleaning for tomorrow at 2 PM", time: "4:00 PM" },
      { id: "m6", sender: "customer", text: "Yes confirmed! See you then", time: "4:30 PM" },
      { id: "m7", sender: "customer", text: "Thank you! The place looks great", time: "6:00 PM" },
    ],
  },
  {
    id: "c3",
    customer: "Adaobi Chen",
    avatar: null,
    lastMessage: "When is the next available date?",
    time: "2 days ago",
    unread: 1,
    messages: [
      { id: "m8", sender: "customer", text: "Hello, I need fumigation for my new apartment", time: "Mon" },
      { id: "m9", sender: "provider", text: "Sure! What size is the apartment?", time: "Mon" },
      { id: "m10", sender: "customer", text: "3 bedroom flat. When is the next available date?", time: "Tue" },
    ],
  },
  {
    id: "c4",
    customer: "Tunde Bakare",
    avatar: null,
    lastMessage: "Okay, I'll book again next month",
    time: "1 week ago",
    unread: 0,
    messages: [
      { id: "m11", sender: "customer", text: "Do you offer monthly cleaning packages?", time: "Last Mon" },
      { id: "m12", sender: "provider", text: "Yes we do! ₦40,000/month for weekly cleaning", time: "Last Mon" },
      { id: "m13", sender: "customer", text: "Okay, I'll book again next month", time: "Last Tue" },
    ],
  },
];

export const MOCK_CALENDAR_EVENTS = [
  { id: "e1", title: "Electrical Wiring", client: "Ada Obi", date: "2026-03-06", time: "1:00 PM", duration: "4h", status: "confirmed" },
  { id: "e2", title: "Deep Cleaning", client: "Emeka Johnson", date: "2026-03-06", time: "9:00 AM", duration: "3h", status: "confirmed" },
  { id: "e3", title: "Home Fumigation", client: "Adaobi Chen", date: "2026-03-08", time: "10:00 AM", duration: "2h", status: "pending" },
  { id: "e4", title: "Deep Cleaning", client: "Tunde Bakare", date: "2026-03-10", time: "11:00 AM", duration: "3h", status: "pending" },
  { id: "e5", title: "Kitchen Renovation", client: "New Client", date: "2026-03-12", time: "9:00 AM", duration: "8h", status: "confirmed" },
  { id: "e6", title: "Electrical Wiring", client: "Grace Obi", date: "2026-03-15", time: "2:00 PM", duration: "3h", status: "confirmed" },
];

export const MOCK_ANALYTICS = {
  bookingsCompleted: 45,
  revenue: 420000,
  conversionRate: 78,
  responseTime: "< 10 min",
  satisfaction: 4.8,
  bookingsTrend: [5, 8, 6, 10, 7, 9, 12],
  revenueTrend: [45000, 62000, 55000, 78000, 68000, 72000, 92000],
  trendLabels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul"],
  popularServices: [
    { name: "Deep Cleaning", bookings: 28, revenue: 420000 },
    { name: "Home Fumigation", bookings: 18, revenue: 360000 },
    { name: "Electrical Wiring", bookings: 12, revenue: 312000 },
    { name: "Kitchen Renovation", bookings: 5, revenue: 600000 },
  ],
};

export const MOCK_SCHEDULE_TODAY = [
  { time: "9:00 AM", service: "Deep Cleaning", client: "Emeka Johnson", status: "confirmed" },
  { time: "1:00 PM", service: "Electrical Wiring", client: "Ada Obi", status: "confirmed" },
  { time: "3:00 PM", service: "Home Fumigation", client: "Grace Obi", status: "pending" },
];
