export const MOCK_SERVICES = [
  {
    id: "ps1",
    name: "Home Fumigation",
    category: "Pest Control",
    price: "₦20,000",
    status: "active" as const,
    bookings: 12,
    rating: 4.8,
  },
  {
    id: "ps2",
    name: "Deep Cleaning",
    category: "Cleaning",
    price: "₦15,000",
    status: "active" as const,
    bookings: 28,
    rating: 4.9,
  },
  {
    id: "ps3",
    name: "Kitchen Renovation",
    category: "Construction",
    price: "₦120,000",
    status: "paused" as const,
    bookings: 5,
    rating: 4.7,
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "pb1",
    service: "Home Fumigation",
    client: "Adaobi Chen",
    date: "2026-02-26",
    time: "10:00 AM",
    status: "pending" as const,
    amount: "₦20,000",
    avatar: null,
  },
  {
    id: "pb2",
    service: "Deep Cleaning",
    client: "Emeka Johnson",
    date: "2026-02-22",
    time: "2:00 PM",
    status: "upcoming" as const,
    amount: "₦15,000",
    avatar: null,
  },
  {
    id: "pb3",
    service: "Kitchen Renovation",
    client: "Sarah Williams",
    date: "2026-02-15",
    time: "9:00 AM",
    status: "completed" as const,
    amount: "₦45,000",
    avatar: null,
  },
  {
    id: "pb4",
    service: "Deep Cleaning",
    client: "Tunde Bakare",
    date: "2026-02-28",
    time: "11:00 AM",
    status: "pending" as const,
    amount: "₦15,000",
    avatar: null,
  },
  {
    id: "pb5",
    service: "Home Fumigation",
    client: "Grace Obi",
    date: "2026-02-10",
    time: "3:00 PM",
    status: "completed" as const,
    amount: "₦20,000",
    avatar: null,
  },
  {
    id: "pb6",
    service: "Kitchen Renovation",
    client: "James Nwachukwu",
    date: "2026-01-30",
    time: "8:00 AM",
    status: "cancelled" as const,
    amount: "₦120,000",
    avatar: null,
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: "pt1",
    title: "Payment — Deep Cleaning",
    date: "Today, 2:30 PM",
    amount: "+ ₦15,000",
    type: "credit" as const,
  },
  {
    id: "pt2",
    title: "Withdrawal to GTBank",
    date: "Feb 19, 2026",
    amount: "- ₦50,000",
    type: "debit" as const,
  },
  {
    id: "pt3",
    title: "Payment — Fumigation",
    date: "Feb 18, 2026",
    amount: "+ ₦20,000",
    type: "credit" as const,
  },
  {
    id: "pt4",
    title: "Commission Fee",
    date: "Feb 18, 2026",
    amount: "- ₦2,000",
    type: "debit" as const,
  },
  {
    id: "pt5",
    title: "Payment — Kitchen Reno",
    date: "Feb 15, 2026",
    amount: "+ ₦45,000",
    type: "credit" as const,
  },
];
