import type { Dispute } from "./types";

// ============================================
// ADMIN MOCK DATA
// ============================================

export const MOCK_PLATFORM_STATS = {
  totalUsers: 12450,
  totalProviders: 890,
  totalBookings: 34200,
  revenue: "₦24.5M",
  activeDisputes: 8,
  pendingProviders: 15,
};

export const MOCK_USERS_LIST = [
  {
    id: "u1",
    name: "Golden Amadi",
    email: "golden@example.com",
    phone: "+234 812 345 6789",
    type: "client" as const,
    status: "active" as const,
    joined: "Jan 15, 2026",
    bookings: 12,
    totalSpent: "₦285,000",
    lastActive: "Today",
    verified: true,
    location: "Lekki, Lagos",
  },
  {
    id: "u2",
    name: "Adaobi Chen",
    email: "adaobi@example.com",
    phone: "+234 803 456 7890",
    type: "client" as const,
    status: "active" as const,
    joined: "Feb 1, 2026",
    bookings: 5,
    totalSpent: "₦128,500",
    lastActive: "Yesterday",
    verified: true,
    location: "Victoria Island, Lagos",
  },
  {
    id: "u3",
    name: "Emeka Johnson",
    email: "emeka@example.com",
    phone: "+234 705 678 1234",
    type: "client" as const,
    status: "suspended" as const,
    joined: "Dec 20, 2025",
    bookings: 0,
    totalSpent: "₦0",
    lastActive: "2 weeks ago",
    verified: false,
    location: "Ikeja, Lagos",
  },
  {
    id: "u4",
    name: "Tunde Bakare",
    email: "tunde@example.com",
    phone: "+234 816 789 0123",
    type: "provider" as const,
    status: "active" as const,
    joined: "Jan 28, 2026",
    bookings: 8,
    totalSpent: "₦192,000",
    lastActive: "2 hours ago",
    verified: true,
    location: "Surulere, Lagos",
  },
  {
    id: "u5",
    name: "Grace Obi",
    email: "grace@example.com",
    phone: "+234 907 234 5678",
    type: "client" as const,
    status: "active" as const,
    joined: "Feb 10, 2026",
    bookings: 3,
    totalSpent: "₦67,500",
    lastActive: "3 days ago",
    verified: true,
    location: "Yaba, Lagos",
  },
  {
    id: "u6",
    name: "Ngozi Eze",
    email: "ngozi@example.com",
    phone: "+234 811 456 2345",
    type: "admin" as const,
    status: "active" as const,
    joined: "Nov 1, 2025",
    bookings: 0,
    totalSpent: "₦0",
    lastActive: "Today",
    verified: true,
    location: "Ikoyi, Lagos",
  },
  {
    id: "u7",
    name: "Chisom Nwosu",
    email: "chisom@example.com",
    phone: "+234 802 345 8901",
    type: "provider" as const,
    status: "active" as const,
    joined: "Dec 5, 2025",
    bookings: 22,
    totalSpent: "₦410,000",
    lastActive: "1 hour ago",
    verified: true,
    location: "Ajah, Lagos",
  },
  {
    id: "u8",
    name: "Adekunle Balogun",
    email: "adekunle@example.com",
    phone: "+234 708 567 1234",
    type: "client" as const,
    status: "banned" as const,
    joined: "Oct 15, 2025",
    bookings: 2,
    totalSpent: "₦35,000",
    lastActive: "1 month ago",
    verified: false,
    location: "Apapa, Lagos",
  },
];

export const MOCK_PROVIDERS_LIST = [
  {
    id: "p1",
    name: "Chinedu Okonkwo",
    email: "chinedu@example.com",
    category: "Electrical",
    status: "verified" as const,
    rating: 4.8,
    jobs: 45,
    joined: "Nov 5, 2025",
  },
  {
    id: "p2",
    name: "CleanPro Services",
    email: "cleanpro@example.com",
    category: "Cleaning",
    status: "verified" as const,
    rating: 4.9,
    jobs: 120,
    joined: "Oct 1, 2025",
  },
  {
    id: "p3",
    name: "AutoCare Mechanics",
    email: "autocare@example.com",
    category: "Automotive",
    status: "pending" as const,
    rating: 0,
    jobs: 0,
    joined: "Feb 18, 2026",
  },
  {
    id: "p4",
    name: "Sarah Beauty Hub",
    email: "sarah@beauty.com",
    category: "Beauty",
    status: "pending" as const,
    rating: 0,
    jobs: 0,
    joined: "Feb 19, 2026",
  },
  {
    id: "p5",
    name: "handi Plumbing",
    email: "handi@plumbing.com",
    category: "Plumbing",
    status: "suspended" as const,
    rating: 3.2,
    jobs: 15,
    joined: "Sep 15, 2025",
  },
];

export const MOCK_DISPUTES: Dispute[] = [
  {
    id: "d1",
    status: "open",
    priority: "high",
    client: "Golden Amadi",
    provider: "handi Plumbing",
    service: "Plumbing Repair",
    amount: "₦12,000",
    date: "Feb 20, 2026",
    category: "Incomplete Work",
    description:
      "Provider left without completing pipe installation. Water is still leaking.",
    providerResponse:
      "Client was not available when I arrived for the second visit to complete the job.",
  },
  {
    id: "d2",
    status: "in-review",
    priority: "medium",
    client: "Adaobi Chen",
    provider: "CleanPro Services",
    service: "Deep Cleaning",
    amount: "₦15,000",
    date: "Feb 18, 2026",
    category: "Quality Issue",
    description:
      "Cleaning quality was poor. Several areas were missed and kitchen was not properly done.",
    providerResponse:
      "We cleaned all areas as agreed. Client added extra rooms that weren't in the original booking.",
  },
  {
    id: "d3",
    status: "resolved",
    priority: "low",
    client: "Tunde Bakare",
    provider: "Chinedu Okonkwo",
    service: "Electrical Wiring",
    amount: "₦25,000",
    date: "Feb 12, 2026",
    category: "Billing Dispute",
    description: "Was charged for materials that weren't used.",
    providerResponse:
      "Materials were purchased and available. Client cancelled part of the job midway.",
    resolution: "Partial refund of ₦5,000 issued to client.",
  },
  {
    id: "d4",
    status: "open",
    priority: "high",
    client: "Grace Obi",
    provider: "Sarah Beauty Hub",
    service: "Bridal Makeup",
    amount: "₦35,000",
    date: "Feb 19, 2026",
    category: "No Show",
    description:
      "Provider did not show up for the appointment. Wedding day was ruined.",
    providerResponse: "",
  },
];

export const MOCK_ACTIVITY = [
  {
    id: "a1",
    text: "New provider application: AutoCare Mechanics",
    time: "2 hours ago",
    type: "provider" as const,
  },
  {
    id: "a2",
    text: "Dispute #d1 opened by Golden Amadi",
    time: "3 hours ago",
    type: "dispute" as const,
  },
  {
    id: "a3",
    text: "New user registered: Fatima Bello",
    time: "5 hours ago",
    type: "user" as const,
  },
  {
    id: "a4",
    text: "Dispute #d3 resolved — partial refund issued",
    time: "1 day ago",
    type: "dispute" as const,
  },
  {
    id: "a5",
    text: "Provider suspended: handi Plumbing (low rating)",
    time: "2 days ago",
    type: "provider" as const,
  },
];
