const fs = require("fs");

const mockApiFile = "C:/HANDI/web/data/mockApi.ts";
const providersFile = "C:/HANDI/web/data/providers.ts";

const newProviders = `
  {
    id: "p13",
    name: "AquaFix Plumbers",
    category: "Plumbing",
    image: "images/providers/provider-image.svg",
    location: "Festac, Lagos",
    rating: 4.8,
    reviews: 112,
    price: "₦5,000 - ₦60,000",
    isOnline: true,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 450,
    skills: ["Pipe Installation", "Water Heater", "Leak Detection"],
    phone: "08000000013",
    bio: "Expert plumbing services for residential and commercial.",
  },
  {
    id: "p14",
    name: "Glow & Go Spa",
    category: "Beauty & Wellness",
    image: "images/providers/provider-image.svg",
    location: "VGC, Lagos",
    rating: 4.9,
    reviews: 245,
    price: "₦10,000 - ₦80,000",
    isOnline: true,
    badge: "Premium",
    providerType: "Business",
    completedJobs: 890,
    skills: ["Massage", "Facials", "Manicure"],
    phone: "08000000014",
    bio: "Premium spa and wellness treatments at your home.",
  },
  {
    id: "p15",
    name: "Handy Dan Services",
    category: "Home Improvement",
    image: "images/providers/provider-image.svg",
    location: "Yaba, Lagos",
    rating: 4.6,
    reviews: 78,
    price: "₦2,000 - ₦30,000",
    isOnline: false,
    badge: null,
    providerType: "Freelancer",
    completedJobs: 120,
    skills: ["TV Mounting", "Furniture Assembly", "Minor Repairs"],
    phone: "08000000015",
    bio: "Quick and reliable handyman for minor tasks.",
  },
  {
    id: "p16",
    name: "Sparkle Cleaners",
    category: "Cleaning",
    image: "images/providers/provider-image.svg",
    location: "Lekki Phase 1, Lagos",
    rating: 4.7,
    reviews: 189,
    price: "₦15,000 - ₦100,000",
    isOnline: true,
    badge: "Top Rated",
    providerType: "Business",
    completedJobs: 650,
    skills: ["Deep Cleaning", "Move-in Clean", "Office Clean"],
    phone: "08000000016",
    bio: "Professional cleaning agency with certified staff.",
  },
  {
    id: "p17",
    name: "Oga Mechanic",
    category: "Automotive",
    image: "images/providers/provider-image.svg",
    location: "Gbagada, Lagos",
    rating: 4.5,
    reviews: 234,
    price: "₦5,000 - ₦150,000",
    isOnline: true,
    badge: "Verified",
    providerType: "Specialist",
    completedJobs: 540,
    skills: ["Engine Scan", "Suspension", "Brakes"],
    phone: "08000000017",
    bio: "Experienced auto mechanic for all Japanese and German cars.",
  },
  {
    id: "p18",
    name: "SafeLife Security",
    category: "Security",
    image: "images/providers/provider-image.svg",
    location: "Ikeja, Lagos",
    rating: 4.8,
    reviews: 67,
    price: "₦20,000 - ₦200,000",
    isOnline: false,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 300,
    skills: ["Escort", "Event Security", "Guard"],
    phone: "08000000018",
    bio: "Trained professional security guards and escorts.",
  },
  {
    id: "p19",
    name: "PestBusters NG",
    category: "Pest Control",
    image: "images/providers/provider-image.svg",
    location: "Surulere, Lagos",
    rating: 4.4,
    reviews: 45,
    price: "₦10,000 - ₦50,000",
    isOnline: true,
    badge: null,
    providerType: "Business",
    completedJobs: 180,
    skills: ["Fumigation", "Bedbugs", "Rodent Control"],
    phone: "08000000019",
    bio: "Eco-friendly pest control services.",
  },
  {
    id: "p20",
    name: "CodeCraft Studios",
    category: "Technology",
    image: "images/providers/provider-image.svg",
    location: "Yaba, Lagos",
    rating: 4.9,
    reviews: 88,
    price: "₦50,000 - ₦500,000",
    isOnline: true,
    badge: "Premium",
    providerType: "Business",
    completedJobs: 210,
    skills: ["Web Design", "App Dev", "SEO"],
    phone: "08000000020",
    bio: "Digital agency for complete technical solutions.",
  },
  {
    id: "p21",
    name: "Urban Movers",
    category: "Moving",
    image: "images/providers/provider-image.svg",
    location: "Ajah, Lagos",
    rating: 4.6,
    reviews: 156,
    price: "₦30,000 - ₦150,000",
    isOnline: false,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 420,
    skills: ["Relocation", "Packing", "Trucking"],
    phone: "08000000021",
    bio: "Hassle-free moving and logistics.",
  },
  {
    id: "p22",
    name: "Chef Chi Catering",
    category: "Event & Party",
    image: "images/providers/provider-image.svg",
    location: "Ikoyi, Lagos",
    rating: 4.9,
    reviews: 312,
    price: "₦100,000 - ₦1,000,000",
    isOnline: true,
    badge: "Top Rated",
    providerType: "Business",
    completedJobs: 890,
    skills: ["Catering", "Small Chops", "Cake"],
    phone: "08000000022",
    bio: "Premium catering for all events.",
  },
  {
    id: "p23",
    name: "CoolBreeze ACs",
    category: "Appliance Repair",
    image: "images/providers/provider-image.svg",
    location: "Oshodi, Lagos",
    rating: 4.7,
    reviews: 198,
    price: "₦5,000 - ₦40,000",
    isOnline: true,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 650,
    skills: ["AC Install", "Gas Refill", "Maintenance"],
    phone: "08000000023",
    bio: "AC repair and installation experts.",
  },
  {
    id: "p24",
    name: "Flora Gardens",
    category: "Gardening",
    image: "images/providers/provider-image.svg",
    location: "Magodo, Lagos",
    rating: 4.5,
    reviews: 34,
    price: "₦10,000 - ₦60,000",
    isOnline: true,
    badge: null,
    providerType: "Freelancer",
    completedJobs: 90,
    skills: ["Lawn Mowing", "Landscaping", "Weeding"],
    phone: "08000000024",
    bio: "Professional landscape and garden maintenance.",
  },
  {
    id: "p25",
    name: "IronWorks Fabricators",
    category: "Construction",
    image: "images/providers/provider-image.svg",
    location: "Agege, Lagos",
    rating: 4.3,
    reviews: 89,
    price: "₦20,000 - ₦500,000",
    isOnline: false,
    badge: null,
    providerType: "Business",
    completedJobs: 150,
    skills: ["Welding", "Gate Fabrication", "Burglary Proof"],
    phone: "08000000025",
    bio: "Custom iron and metal fabricators.",
  },
  {
    id: "p26",
    name: "Yoga with Yemisi",
    category: "Fitness",
    image: "images/providers/provider-image.svg",
    location: "Lekki, Lagos",
    rating: 4.9,
    reviews: 145,
    price: "₦15,000 - ₦80,000",
    isOnline: true,
    badge: "Premium",
    providerType: "Specialist",
    completedJobs: 320,
    skills: ["Yoga", "Meditation", "Pilates"],
    phone: "08000000026",
    bio: "Private yoga and mindfulness sessions.",
  },
  {
    id: "p27",
    name: "Swift Logistics",
    category: "Moving",
    image: "images/providers/provider-image.svg",
    location: "Apapa, Lagos",
    rating: 4.4,
    reviews: 211,
    price: "₦15,000 - ₦100,000",
    isOnline: true,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 800,
    skills: ["Delivery", "Haulage", "Transport"],
    phone: "08000000027",
    bio: "Nationwide package and freight delivery.",
  },
  {
    id: "p28",
    name: "ElectroFix Bros",
    category: "Electrical",
    image: "images/providers/provider-image.svg",
    location: "Mushin, Lagos",
    rating: 4.6,
    reviews: 76,
    price: "₦3,000 - ₦30,000",
    isOnline: false,
    badge: null,
    providerType: "Specialist",
    completedJobs: 250,
    skills: ["Wiring", "Fan Install", "Lighting"],
    phone: "08000000028",
    bio: "Certified electricians for home faults.",
  },
  {
    id: "p29",
    name: "Mama's Kitchen",
    category: "Event & Party",
    image: "images/providers/provider-image.svg",
    location: "Surulere, Lagos",
    rating: 4.8,
    reviews: 432,
    price: "₦50,000 - ₦500,000",
    isOnline: true,
    badge: "Top Rated",
    providerType: "Business",
    completedJobs: 1100,
    skills: ["Jollof", "Soups", "Local Dishes"],
    phone: "08000000029",
    bio: "Authentic Nigerian party food catering.",
  },
  {
    id: "p30",
    name: "Lagos Car Wash",
    category: "Automotive",
    image: "images/providers/provider-image.svg",
    location: "Victoria Island, Lagos",
    rating: 4.7,
    reviews: 567,
    price: "₦3,000 - ₦15,000",
    isOnline: true,
    badge: "Premium",
    providerType: "Business",
    completedJobs: 3000,
    skills: ["Detailing", "Polishing", "Washing"],
    phone: "08000000030",
    bio: "Premium auto detailing and steam wash.",
  },
  {
    id: "p31",
    name: "Digital Dreams",
    category: "Technology",
    image: "images/providers/provider-image.svg",
    location: "Ikeja, Lagos",
    rating: 4.8,
    reviews: 123,
    price: "₦100,000 - ₦2,000,000",
    isOnline: true,
    badge: "Verified",
    providerType: "Business",
    completedJobs: 280,
    skills: ["UI/UX", "Branding", "Dev"],
    phone: "08000000031",
    bio: "Digital product design and development.",
  },
  {
    id: "p32",
    name: "Perfect Polish Painters",
    category: "Home Improvement",
    image: "images/providers/provider-image.svg",
    location: "Ajah, Lagos",
    rating: 4.5,
    reviews: 88,
    price: "₦20,000 - ₦300,000",
    isOnline: true,
    badge: null,
    providerType: "Business",
    completedJobs: 140,
    skills: ["Painting", "Screeding", "Wallpaper"],
    phone: "08000000032",
    bio: "Transforming homes with color.",
  }
`;

const newServices = `
  {
    id: "s13",
    name: "Water Leak Repair",
    provider: "AquaFix Plumbers",
    providerId: "p13",
    category: "plumbing",
    rating: 4.8,
    reviews: 112,
    price: 15000,
    originalPrice: 20000,
    image: "/images/services/plumbing.svg",
    location: "Festac, Lagos",
    duration: "1-2 hours",
    description: "Expert leak detection and repair.",
    policies: "Parts cost extra."
  },
  {
    id: "s14",
    name: "Full Body Massage",
    provider: "Glow & Go Spa",
    providerId: "p14",
    category: "beauty",
    rating: 4.9,
    reviews: 245,
    price: 25000,
    originalPrice: 35000,
    image: "/images/services/massage.svg",
    location: "VGC, Lagos",
    duration: "90 mins",
    description: "Relaxing full body swedish massage.",
    policies: "Book 24hrs ahead."
  },
  {
    id: "s15",
    name: "TV Mounting",
    provider: "Handy Dan Services",
    providerId: "p15",
    category: "home-improvement",
    rating: 4.6,
    reviews: 78,
    price: 10000,
    originalPrice: 15000,
    image: "/images/services/tv-mounting.svg",
    location: "Yaba, Lagos",
    duration: "1 hour",
    description: "Secure wall mounting for TVs up to 65'.",
    policies: "Bracket not included."
  },
  {
    id: "s16",
    name: "Move-in Cleaning",
    provider: "Sparkle Cleaners",
    providerId: "p16",
    category: "cleaning",
    rating: 4.7,
    reviews: 189,
    price: 30000,
    originalPrice: 40000,
    image: "/images/services/move-in-cleaning.svg",
    location: "Lekki Phase 1, Lagos",
    duration: "4-6 hours",
    description: "Deep cleaning for empty apartments before move-in.",
    policies: "None."
  },
  {
    id: "s17",
    name: "Car Engine Diagnosis",
    provider: "Oga Mechanic",
    providerId: "p17",
    category: "automotive",
    rating: 4.5,
    reviews: 234,
    price: 15000,
    originalPrice: 20000,
    image: "/images/services/car-diagnostics.svg",
    location: "Gbagada, Lagos",
    duration: "1-2 hours",
    description: "Comprehensive engine computer diagnosis.",
    policies: "None."
  },
  {
    id: "s18",
    name: "Security Guard Escort",
    provider: "SafeLife Security",
    providerId: "p18",
    category: "security",
    rating: 4.8,
    reviews: 67,
    price: 50000,
    originalPrice: 60000,
    image: "/images/services/security.svg",
    location: "Ikeja, Lagos",
    duration: "8 hours",
    description: "Trained personal security detail.",
    policies: "Subject to verification."
  },
  {
    id: "s19",
    name: "Fumigation Service",
    provider: "PestBusters NG",
    providerId: "p19",
    category: "fumigation",
    rating: 4.4,
    reviews: 45,
    price: 20000,
    originalPrice: 25000,
    image: "/images/services/fumigation.svg",
    location: "Surulere, Lagos",
    duration: "2-3 hours",
    description: "Eradicate mosquitoes, roaches, and rodents.",
    policies: "Vacate premises for 4 hours."
  },
  {
    id: "s20",
    name: "Website Development",
    provider: "CodeCraft Studios",
    providerId: "p20",
    category: "technology",
    rating: 4.9,
    reviews: 88,
    price: 150000,
    originalPrice: 200000,
    image: "/images/services/web-development.svg",
    location: "Yaba, Lagos",
    duration: "2 weeks",
    description: "Custom 5-page business website built from scratch.",
    policies: "50% upfront."
  },
  {
    id: "s21",
    name: "Apartment Relocation",
    provider: "Urban Movers",
    providerId: "p21",
    category: "moving",
    rating: 4.6,
    reviews: 156,
    price: 80000,
    originalPrice: 100000,
    image: "/images/services/moving.svg",
    location: "Ajah, Lagos",
    duration: "4-8 hours",
    description: "Full truck and men to pack and move your home.",
    policies: "Insurance covered."
  },
  {
    id: "s22",
    name: "Wedding Catering",
    provider: "Chef Chi Catering",
    providerId: "p22",
    category: "event",
    rating: 4.9,
    reviews: 312,
    price: 500000,
    originalPrice: 600000,
    image: "/images/services/catering.svg",
    location: "Ikoyi, Lagos",
    duration: "1 day",
    description: "Premium catering for up to 300 guests.",
    policies: "Menu customization."
  },
  {
    id: "s23",
    name: "Fridge Gas Refill",
    provider: "CoolBreeze ACs",
    providerId: "p23",
    category: "appliance",
    rating: 4.7,
    reviews: 198,
    price: 12000,
    originalPrice: 15000,
    image: "/images/services/fridge.svg",
    location: "Oshodi, Lagos",
    duration: "1-2 hours",
    description: "Refrigerant gas top-up and leak seal.",
    policies: "1-month guarantee."
  },
  {
    id: "s24",
    name: "Lawn Mowing",
    provider: "Flora Gardens",
    providerId: "p24",
    category: "gardening",
    rating: 4.5,
    reviews: 34,
    price: 15000,
    originalPrice: 20000,
    image: "/images/services/landscaping.svg",
    location: "Magodo, Lagos",
    duration: "2 hours",
    description: "Standard lawn mowing and trimming.",
    policies: "None."
  },
  {
    id: "s25",
    name: "Gate Fabrication",
    provider: "IronWorks Fabricators",
    providerId: "p25",
    category: "construction",
    rating: 4.3,
    reviews: 89,
    price: 150000,
    originalPrice: 180000,
    image: "/images/services/welding.svg",
    location: "Agege, Lagos",
    duration: "1 week",
    description: "Custom iron gate building and installation.",
    policies: "Material costs separate."
  },
  {
    id: "s26",
    name: "Private Yoga Session",
    provider: "Yoga with Yemisi",
    providerId: "p26",
    category: "fitness",
    rating: 4.9,
    reviews: 145,
    price: 15000,
    originalPrice: 20000,
    image: "/images/services/yoga.svg",
    location: "Lekki, Lagos",
    duration: "1 hour",
    description: "One-on-one yoga instruction.",
    policies: "Cancellation fee applies."
  },
  {
    id: "s27",
    name: "Inter-state Delivery",
    provider: "Swift Logistics",
    providerId: "p27",
    category: "moving",
    rating: 4.4,
    reviews: 211,
    price: 35000,
    originalPrice: 45000,
    image: "/images/services/delivery.svg",
    location: "Apapa, Lagos",
    duration: "1-3 days",
    description: "Secure delivery to neighboring states.",
    policies: "Items must be legal."
  },
  {
    id: "s28",
    name: "Ceiling Fan Installation",
    provider: "ElectroFix Bros",
    providerId: "p28",
    category: "electrical",
    rating: 4.6,
    reviews: 76,
    price: 8000,
    originalPrice: 10000,
    image: "/images/services/electrical.svg",
    location: "Mushin, Lagos",
    duration: "1-2 hours",
    description: "Safe and secure fan mounting.",
    policies: "None."
  },
  {
    id: "s29",
    name: "Party Jollof Rice (Cooler)",
    provider: "Mama's Kitchen",
    providerId: "p29",
    category: "event",
    rating: 4.8,
    reviews: 432,
    price: 45000,
    originalPrice: 50000,
    image: "/images/services/catering.svg",
    location: "Surulere, Lagos",
    duration: "Pre-order",
    description: "Large cooler of authentic party Jollof.",
    policies: "24hr notice required."
  },
  {
    id: "s30",
    name: "Full Auto Detailing",
    provider: "Lagos Car Wash",
    providerId: "p30",
    category: "automotive",
    rating: 4.7,
    reviews: 567,
    price: 25000,
    originalPrice: 35000,
    image: "/images/services/car-wash.svg",
    location: "Victoria Island, Lagos",
    duration: "3 hours",
    description: "Inside out deep clean and polish.",
    policies: "None."
  },
  {
    id: "s31",
    name: "Mobile App Wireframing",
    provider: "Digital Dreams",
    providerId: "p31",
    category: "technology",
    rating: 4.8,
    reviews: 123,
    price: 80000,
    originalPrice: 100000,
    image: "/images/services/design.svg",
    location: "Ikeja, Lagos",
    duration: "1 week",
    description: "UX/UI wireframes for your app idea.",
    policies: "3 revisions included."
  },
  {
    id: "s32",
    name: "House Interior Painting",
    provider: "Perfect Polish Painters",
    providerId: "p32",
    category: "home-improvement",
    rating: 4.5,
    reviews: 88,
    price: 50000,
    originalPrice: 70000,
    image: "/images/services/painting.svg",
    location: "Ajah, Lagos",
    duration: "2-4 days",
    description: "Professional painting of a 2-bedroom standard flat.",
    policies: "Paint not included."
  }
`;

const newFlashDeals = `
  {
    id: "d4",
    name: "Emergency Plumbing Repair",
    provider: "FastFix Plumbing",
    original: 15000,
    sale: 10000,
    discount: 33,
    rating: 4.7,
    booked: 45,
    image: "/images/services/plumbing.svg"
  },
  {
    id: "d5",
    name: "Full Spa Treatment",
    provider: "QueenB Beauty Lounge",
    original: 40000,
    sale: 25000,
    discount: 37,
    rating: 4.9,
    booked: 89,
    image: "/images/services/massage.svg"
  },
  {
    id: "d6",
    name: "Generator Tune-up",
    provider: "TechMasters NG",
    original: 25000,
    sale: 18000,
    discount: 28,
    rating: 4.6,
    booked: 67,
    image: "/images/services/generator-service.svg"
  },
  {
    id: "d7",
    name: "Home Fumigation",
    provider: "PestBusters NG",
    original: 30000,
    sale: 20000,
    discount: 33,
    rating: 4.5,
    booked: 112,
    image: "/images/services/fumigation.svg"
  },
  {
    id: "d8",
    name: "Sofa Dry Cleaning",
    provider: "CleanPro Services",
    original: 20000,
    sale: 12000,
    discount: 40,
    rating: 4.8,
    booked: 156,
    image: "/images/services/cleaning.svg"
  },
  {
    id: "d9",
    name: "Brake Pad Replacement",
    provider: "AutoCare Mechanics",
    original: 18000,
    sale: 13000,
    discount: 27,
    rating: 4.4,
    booked: 78,
    image: "/images/services/car-diagnostics.svg"
  },
  {
    id: "d10",
    name: "AC Gas Top-up",
    provider: "CoolBreeze ACs",
    original: 12000,
    sale: 8000,
    discount: 33,
    rating: 4.7,
    booked: 234,
    image: "/images/services/ac-service.svg"
  },
  {
    id: "d11",
    name: "Wall Painting (1 Room)",
    provider: "HomeStyle Interiors",
    original: 35000,
    sale: 25000,
    discount: 28,
    rating: 4.9,
    booked: 45,
    image: "/images/services/painting.svg"
  },
  {
    id: "d12",
    name: "Bridal Makeup",
    provider: "Glow & Go Spa",
    original: 80000,
    sale: 50000,
    discount: 37,
    rating: 4.9,
    booked: 23,
    image: "/images/services/massage.svg"
  },
  {
    id: "d13",
    name: "Personal Chef (Weekend)",
    provider: "Chef Chi Catering",
    original: 100000,
    sale: 75000,
    discount: 25,
    rating: 4.9,
    booked: 34,
    image: "/images/services/tailoring.svg"
  },
  {
    id: "d14",
    name: "Office Server Setup",
    provider: "CodeCraft Studios",
    original: 150000,
    sale: 100000,
    discount: 33,
    rating: 4.8,
    booked: 12,
    image: "/images/services/event-photography.svg"
  },
  {
    id: "d15",
    name: "Security Consult",
    provider: "SafeLife Security",
    original: 20000,
    sale: 10000,
    discount: 50,
    rating: 4.8,
    booked: 56,
    image: "/images/services/security.svg"
  },
  {
    id: "d16",
    name: "Moving Truck (Half Day)",
    provider: "Urban Movers",
    original: 60000,
    sale: 45000,
    discount: 25,
    rating: 4.6,
    booked: 89,
    image: "/images/services/logistics.svg"
  },
  {
    id: "d17",
    name: "TV Wall Mounting",
    provider: "Handy Dan Services",
    original: 15000,
    sale: 10000,
    discount: 33,
    rating: 4.6,
    booked: 167,
    image: "/images/services/tv-mounting.svg"
  },
  {
    id: "d18",
    name: "Generator Service",
    provider: "Adebayo Electricals",
    original: 12000,
    sale: 8000,
    discount: 33,
    rating: 4.8,
    booked: 211,
    image: "/images/services/generator-service.svg"
  },
  {
    id: "d19",
    name: "Carpet Deep Clean",
    provider: "CleanPro Services",
    original: 30000,
    sale: 20000,
    discount: 33,
    rating: 4.7,
    booked: 145,
    image: "/images/services/cleaning.svg"
  },
  {
    id: "d20",
    name: "Ceramic Car Coating",
    provider: "Lagos Car Wash",
    original: 150000,
    sale: 100000,
    discount: 33,
    rating: 4.7,
    booked: 34,
    image: "/images/services/car-service.svg"
  },
  {
    id: "d21",
    name: "1-Month Gym Access",
    provider: "FitLife Personal Training",
    original: 30000,
    sale: 20000,
    discount: 33,
    rating: 4.7,
    booked: 189,
    image: "/images/services/yoga.svg"
  },
  {
    id: "d22",
    name: "Compound Weeding",
    provider: "Flora Gardens",
    original: 15000,
    sale: 10000,
    discount: 33,
    rating: 4.5,
    booked: 76,
    image: "/images/services/landscaping.svg"
  },
  {
    id: "d23",
    name: "Logo Design",
    provider: "Digital Dreams",
    original: 50000,
    sale: 30000,
    discount: 40,
    rating: 4.8,
    booked: 67,
    image: "/images/services/design.svg"
  }
`;

let pStr = fs.readFileSync(providersFile, "utf8");
pStr = pStr.replace(
  /(export const MOCK_PROVIDERS: Provider\\[\\] = \\[[\\s\\S]*?)(];)/,
  (match, p1, p2) => {
    return p1 + "," + newProviders + "\\n" + p2;
  },
);
fs.writeFileSync(providersFile, pStr);

let aStr = fs.readFileSync(mockApiFile, "utf8");
aStr = aStr.replace(
  /(export const MOCK_SERVICES: Service\\[\\] = \\[[\\s\\S]*?)(];)/,
  (match, p1, p2) => {
    return p1 + "," + newServices + "\\n" + p2;
  },
);
aStr = aStr.replace(
  /export const MOCK_FLASH_DEALS: FlashDeal\\[\\] = \\[[\\s\\S]*?];/,
  (match) => match.replace(/(];)$/, "," + newFlashDeals + "\\n$1"),
);

// MOCK_FLASH_DEALS might not exist in the file at all beforehand
if (!aStr.includes("export const MOCK_FLASH_DEALS")) {
  aStr +=
    "\\n// ================================\\n// Mock Flash Deals\\n// ================================\\nexport const MOCK_FLASH_DEALS: FlashDeal[] = [" +
    newFlashDeals +
    "\\n];\\n";
}

fs.writeFileSync(mockApiFile, aStr);

console.log("Mock data successfully appended without glitching!");
